# Site
name: "BOOSTALSS"
title: "BOOSTALSS"
description: "Let's Study algorithms!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'boostalss'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  happyBeagle:
    name: Jo Min Jung
    display_name: happyBeagle
    gravatar: fac2239fb739a49a376a874dde21dd71
    email: hack2kong@gmail.com
    web: https://happybeagle.github.io/
    description: "Enjoying learning new things. Interested in embedded, AI, algorithms, backend"
  Lala:
    name: Joo Young Lee
    display_name: Lala
    email: vvvic313@gmail.com
    web: https://github.com/Lala-chick
    description: "Enjoying learning new things. Interested in AI, computer vision, health care"
  nureesong:
    name: Nu Ree Song
    display_name: nuree
    email: nuri3136@naver.com
    web: https://github.com/nureesong
    description: "Enjoying learning new things. Interested in Computer vision, ML, Applied mathematics"
  H_MiNi:
    name: Hyeong Min Kim
    display_name: H_MiNi
    email: doritos2498@gmail.com
    web: https://github.com/doritos0812
    description: "Flexible-Thinking Developer. AI Engineer DREAM TREE"
    
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
